# Generated by Django 3.2.20 on 2025-03-24 16:06
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelogue_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venueid', models.CharField(max_length=50)),
                ('distance', models.FloatField()),
                ('parentnodeid', models.IntegerField()),
                ('level', models.IntegerField()),
                ('nodeid', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='travelogue',
            name='date',
            field=models.DateField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(),
        ),
    ]
