# Generated by Django 3.2.20 on 2025-03-24 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelogue_app', '0002_auto_20250324_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='neg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='neu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='pos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='photo1',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='place',
            name='CATEGORY',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travelogue_app.category'),
            preserve_default=False,
        ),
    ]
