# Generated by Django 3.2.20 on 2025-03-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelogue_app', '0003_auto_20250325_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='photo',
            field=models.CharField(max_length=250),
        ),
    ]
