# Generated by Django 3.2.20 on 2025-03-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelogue_app', '0004_alter_facility_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='neg',
        ),
        migrations.RemoveField(
            model_name='review',
            name='neu',
        ),
        migrations.RemoveField(
            model_name='review',
            name='pos',
        ),
        migrations.AddField(
            model_name='place',
            name='neg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='neu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='pos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.CharField(max_length=250),
        ),
    ]
