# Generated by Django 3.2.20 on 2025-03-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelogue_app', '0005_auto_20250325_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='place',
            field=models.CharField(max_length=100),
        ),
    ]
